version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://db:27017/mydatabase
    depends_on:
      - db

db:
  image: mongo:latest
  ports:
    - "27017:27017"      
  volumes:
    - mongodb_data:/data/db

volumes:
  mongodb_data:
